### ISSUE TITLE
Crash clicking checkmark when writing comment

### ISSUE THREAD

**Issue by chefexperte** [danilkinkin/buckwheat#88]
**Describe the bug**
When adding a new comment in the app, the app crashes when clicking on the checkmark. 
If I click somewhere else on the screen to close the input field, it does not crash. 

**To Reproduce**
1. Open App
2. Click on Comment
3. Click Checkmark
4. Crash

However, I am not able to reproduce this every time. It only happens sometimes. I hope the crashlog is somewhat useful. 

**Expected behavior**
The comment should be saved

**Screenshots**
![Screenshot_20230923-143541_Buckwheat](https://github.com/danilkinkin/buckwheat/assets/12102112/1dc17880-e94b-4e5a-9c06-7b3bb07ae7f1)

**Please complete the following information:**
 - Device: Pocophone F1
 - OS: Android13
 - Version 3.16.0

**Additional context**

<summary> 
<details>

```
time: 1695472090114
msg: java.lang.IllegalStateException: Event can't be processed because we do not have an active focus target.
stacktrace: java.lang.IllegalStateException: Event can't be processed because we do not have an active focus target.
	at androidx.compose.ui.platform.AndroidComposeView.dispatchKeyEvent(Unknown Source:661)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1965)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:488)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1906)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4277)
	at et.dispatchKeyEvent(Unknown Source:24)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:402)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6713)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6579)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6255)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6435)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3651)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3171)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3162)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3628)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7936)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)

```

</summary> 
</details>

**Comment by danilkinkin** [comment]
Hi, I was not able to quickly reproduce this bug, but I roughly understand where it is happening. I'll try to reproduce it later and fix it, thanks

**Comment by chefexperte** [comment]
Yeah, as I said, I also was not able to reproduce it with success, but I thought it might still be worth looking at.

**Comment by danielyrovas** [comment]
I believe I get the same crash when hitting `enter` (in the emulator) after writing a comment.

**Comment by hmmmIndeed** [comment]
I'm getting the same or a similar crash when I create a tag but it happens every time I try to create the tab with either of those two buttons in the image below. Sometimes it doesn't crash when I use my keyboard's `enter` button.

I'm not sure if this matters but the keyboard I'm using is Florisboard.

* Device: Google Pixel 7
* OS: Android 15 (GrapheneOS)

![Screenshot_20250113-215843](https://github.com/user-attachments/assets/f5486197-30d1-402f-9fca-803fe7d1e31d)
Here are my logs relating to the crash:
``````
type: crash
osVersion: google/panther/panther:15/AP4A.250105.002/2025010700:user/release-keys
flags: dev options enabled
package: com.danilkinkin.buckwheat:28, targetSdk 34
process: com.danilkinkin.buckwheat
processUptime: 79917 + 272 ms
installer: org.fdroid.fdroid

java.lang.IllegalStateException: LayoutCoordinate operations are only valid when isAttached is true
	at kH.q(Unknown Source:28)
	at lr.A(Unknown Source:0)
	at vL.p(Unknown Source:125)
	at ri.a(Unknown Source:34)
	at JN.requestCursorUpdates(Unknown Source:107)
	at android.view.inputmethod.InputConnection.requestCursorUpdates(InputConnection.java:1260)
	at android.view.inputmethod.RemoteInputConnectionImpl.requestCursorUpdatesInternal(RemoteInputConnectionImpl.java:1109)
	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$requestCursorUpdates$41(RemoteInputConnectionImpl.java:1071)
	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$z-R71fdG3JYWpp8pqgPpN3aJVEk(Unknown Source:0)
	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda47.get(D8$$SyntheticClass:0)
	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$dispatchWithTracing$49(RemoteInputConnectionImpl.java:1447)
	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$2C56kBNyimaX29P3MVRhxNO0E2M(Unknown Source:0)
	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda35.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

```
